sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t elliotgonzalez/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true elliotgonzalez/docker-react-test npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'test'
  env: 'test'
  bucket_name: 'test'
  bucket_path: 'docker-react-test'
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
