sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t elliotgonzalez/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true elliotgonzalez/docker-react-test npm run test
